language: haskell
branches:
  only:
  - master
ghc:
- 7.6
install:
- cabal sandbox init
- cabal install -j hakyll
before_script:
- cd _bin
- git checkout gh-pages
- git pull origin gh-pages
- cd ..
- rm -f /_bin/hakyll-sandbox.tar.gz
script: tar -zcvf  ./_bin/hakyll-sandbox.tar.gz ./.cabal-sandbox
after_script:
- cd _bin
- git status
- git add hakyll-sandbox.tar.gz
- git config --global user.email "joey@eremondi.com"
- git config --global user.name "JoeyEremondi"
- git commit -m "snapshot $(date '+%m/%d/%y %H:%M')"
- git push "$HAKYLL_SANDBOX_URL" gh-pages >/dev/null 2>&1
- cd ..
